name : deploy dist folder 
on : push
jobs :
  test : 
    runs-on : ubuntu-latest 
    steps :
      - name : getcode
        uses : actions/checkout@v4
      - name : instll node js 
        uses : actions/setup-node@v4
        with :
           node-version : 22
      - name : print node vesrion 
        run : node -v
      - name : install dependencies 
        run : npm install 
      - name : run test 
        run : npm run test 
      - name : complete job 
        run : echo "job completed"
  build : 
    needs : test
    runs-on : ubuntu-latest
    steps : 
      - name : get code 
        uses : actions/checkout@v4
      - name : install node js
        uses : actions/setup-node@v4
        with : 
          node-version : 22
      - name : install dependencies 
        run : npm install 
      - name : run build 
        run : npm run build
      - name : complete build job
        run : echo "build job completed"



